# ОРГАНИЗАЦИЯ
source = ~/.config/hypr/organized/monitor.conf
source = ~/.config/hypr/organized/variables.conf
source = ~/.config/hypr/organized/autostart.conf
source = ~/.config/hypr/organized/env.conf
source = ~/.config/hypr/organized/permissions.conf
source = ~/.config/hypr/organized/lookandfeel.conf
source = ~/.config/hypr/organized/input.conf
source = ~/.config/hypr/organized/binds.conf
# WALLPAPER
exec-once = hyprpaper
exec-once = sleep 0.5 && hyprctl hyprpaper preload /home/dj/Downloads/wallhaven-4216zx.jpg
exec-once = sleep 1 && hyprctl hyprpaper wallpaper "eDP-1,/home/dj/Downloads/wallhaven-4216zx.jpg"
exec-once = sleep 1 && hyprctl hyprpaper wallpaper "DP-4,/home/dj/Downloads/wallhaven-4216zx.jpg"
# CURSOR
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24

# --- Resize (tiled) ---
bind = $mainMod, H, resizeactive, -20 0
bind = $mainMod, L, resizeactive, 20 0
bind = $mainMod, K, resizeactive, 0 -20
bind = $mainMod, J, resizeactive, 0 20

# --- Toggle floating ---
bind = $mainMod, V, togglefloating,

# --- Mouse resize (floating) ---
bindm = $mainMod, mouse:273, resizewindow

# --- Compact gaps ---
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
}

